### ISSUE TITLE
bug:  Windows unable to run prettier from node_modules

### ISSUE THREAD

**Issue by bartektelec** [stevearc/conform.nvim#236]
### Neovim version (nvim -v)

0.9,1

### Operating system/version

Windows 11 22H2

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

Formatter 'prettier' error in jobstart: Vim:E903: Process failed to start: no such file or directory: "D:/projects/projectName/src/ClientApp/node_modules/.bin/prettier"

### Describe the bug

Conform wasn't able to run prettier of node_modules, same thing happened on two different PCs. 
There was a file called "prettier" (together with prettier.cmd and prettier.ps1) in my `node_modules/.bin` but it couldn't run it. I ended up overriding conform's `util.lua` file and added ` .. ".cmd" ` at the end of the path. After that it started running just fine.

### Steps To Reproduce

1. Run neovim with LazyVim basic setup on a Windows machine
2. Add formatting.prettier through LazyExtras
3. Try format any TypeScript file.

### Expected Behavior

Should just format the file as usual

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/conform.nvim",
    config = function()
      require("conform").setup({
        log_level = vim.log.levels.DEBUG,
        -- add your config here
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### Additional context

running of git-bash / zsh

**Comment by GitMurf** [comment]
I have a related error with Windows path issues but actually think it is a bit different. If I have a space in my path at all of my git repository (where prettier is installed in node_modules) then I get the following error:

![image](https://github.com/stevearc/conform.nvim/assets/64155612/4caf78f5-6705-402e-9a03-4733245efedf)

Notice the actual start to my path to my git repo locally has a space here which is exactly where the error above cutoff.

![image](https://github.com/stevearc/conform.nvim/assets/64155612/a2ed4b4a-bbd8-490b-88ad-8b0adc3b889a)

**Comment by GitMurf** [comment]
If I take the exact same project and simply clone it to like c:/temp on my windows machine (no spaces then in path) then everything works fine.

**Comment by stevearc** [comment]
I believe the issue with using the `.cmd` binary should be fixed. @GitMurf please file a new issue if you're still having trouble with spaces in the path

**Comment by GitMurf** [comment]
@stevearc it is still not working so I opened a new issue #252
